spring.application.name=formerjob

spring.datasource.url=jdbc:postgresql://localhost:5432/formerjob
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always
spring.jpa.show-sql=false
server.port=8080

spring.jpa.defer-datasource-initialization=true

spring.sql.init.encoding=UTF-8
spring.sql.init.platform=postgresql
spring.sql.init.data-locations=classpath:data.sql
spring.sql.init.continue-on-error=false

spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true

# ============================
#  Mailtrap SMTP (test only)
# ============================
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=bdc206156b0144
spring.mail.password=47ed5222e527f3
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.debug=true
spring.mail.default-encoding=UTF-8

# Mittente logico
app.mail.from=prova@gestionale.local

# Profilo attivo - cambia in "prod" per produzione
spring.profiles.active=dev

# Cloudinary
cloudinary.cloud-name=dstpobuge
cloudinary.api-key=578733462843927
cloudinary.api-secret=FiwS5H_5RbyCXkQ8SuRlQhjcwLA